# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180805_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentryfile',
            name='blog_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='blog.BlogEntry'),
        ),
    ]
