# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-13 06:13
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180805_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogentry',
            name='likes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=list, help_text='users id', size=None),
        ),
        migrations.AlterField(
            model_name='blogentry',
            name='link',
            field=models.URLField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
